## 5 Importing Standard Earth Science Datasets
## 5.1 Text

In [120]:
from pathlib import Path

import h5py
import numpy as np
import pandas as pd
import pygrib
import xarray as xr
from netCDF4 import Dataset

In [64]:
filename = "20250101_20250131_CalTech.lev20"
aeronet_file = Path("./data/txt") / filename
aeronet = pd.read_csv(aeronet_file, skiprows=6)

In [65]:
aeronet.head()

,Date(dd:mm:yyyy),Time(hh:mm:ss),Day_of_Year,Day_of_Year(Fraction),AOD_1640nm,AOD_1020nm,AOD_870nm,AOD_865nm,AOD_779nm,AOD_675nm,...,Exact_Wavelengths_of_AOD(um)_380nm,Exact_Wavelengths_of_AOD(um)_340nm,Exact_Wavelengths_of_PW(um)_935nm,Exact_Wavelengths_of_AOD(um)_681nm,Exact_Wavelengths_of_AOD(um)_709nm,Exact_Wavelengths_of_AOD(um)_Empty,Exact_Wavelengths_of_AOD(um)_Empty.1,Exact_Wavelengths_of_AOD(um)_Empty.2,Exact_Wavelengths_of_AOD(um)_Empty.3,Exact_Wavelengths_of_AOD(um)_Empty.4
0,01:01:2025,15:51:37,1,1.660845,0.006693,0.014841,0.017032,-999.0,-999.0,0.022185,...,0.379158,0.339815,0.937502,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
1,01:01:2025,15:54:10,1,1.662616,0.006835,0.015043,0.016874,-999.0,-999.0,0.022377,...,0.379158,0.339815,0.937502,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
2,01:01:2025,15:56:38,1,1.664329,0.006976,0.015269,0.017126,-999.0,-999.0,0.022490,...,0.379158,0.339815,0.937502,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
3,01:01:2025,15:58:36,1,1.665694,0.007513,0.015661,0.017646,-999.0,-999.0,0.022898,...,0.379158,0.339815,0.937502,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
4,01:01:2025,16:01:37,1,1.667789,0.006747,0.014947,0.017023,-999.0,-999.0,0.022029,...,0.379158,0.339815,0.937502,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0

In [66]:
list(aeronet.columns)

['Date(dd:mm:yyyy)',
 'Time(hh:mm:ss)',
 'Day_of_Year',
 'Day_of_Year(Fraction)',
 'AOD_1640nm',
 'AOD_1020nm',
 'AOD_870nm',
 'AOD_865nm',
 'AOD_779nm',
 'AOD_675nm',
 'AOD_667nm',
 'AOD_620nm',
 'AOD_560nm',
 'AOD_555nm',
 'AOD_551nm',
 'AOD_532nm',
 'AOD_531nm',
 'AOD_510nm',
 'AOD_500nm',
 'AOD_490nm',
 'AOD_443nm',
 'AOD_440nm',
 'AOD_412nm',
 'AOD_400nm',
 'AOD_380nm',
 'AOD_340nm',
 'Precipitable_Water(cm)',
 'AOD_681nm',
 'AOD_709nm',
 'AOD_Empty',
 'AOD_Empty.1',
 'AOD_Empty.2',
 'AOD_Empty.3',
 'AOD_Empty.4',
 'Triplet_Variability_1640',
 'Triplet_Variability_1020',
 'Triplet_Variability_870',
 'Triplet_Variability_865',
 'Triplet_Variability_779',
 'Triplet_Variability_675',
 'Triplet_Variability_667',
 'Triplet_Variability_620',
 'Triplet_Variability_560',
 'Triplet_Variability_555',
 'Triplet_Variability_551',
 'Triplet_Variability_532',
 'Triplet_Variability_531',
 'Triplet_Variability_510',
 'Triplet_Variability_500',
 'Triplet_Variability_490',
 'Triplet_Variability_443',
 'Triplet_Variability_440',
 'Triplet_Variability_412',
 'Triplet_Variability_400',
 'Triplet_Variability_380',
 'Triplet_Variability_340',
 'Triplet_Variability_Precipitable_Water(cm)',
 'Triplet_Variability_681',
 'Triplet_Variability_709',
 'Triplet_Variability_AOD_Empty',
 'Triplet_Variability_AOD_Empty.1',
 'Triplet_Variability_AOD_Empty.2',
 'Triplet_Variability_AOD_Empty.3',
 'Triplet_Variability_AOD_Empty.4',
 '440-870_Angstrom_Exponent',
 '380-500_Angstrom_Exponent',
 '440-675_Angstrom_Exponent',
 '500-870_Angstrom_Exponent',
 '340-440_Angstrom_Exponent',
 '440-675_Angstrom_Exponent[Polar]',
 'Data_Quality_Level',
 'AERONET_Instrument_Number',
 'AERONET_Site_Name',
 'Site_Latitude(Degrees)',
 'Site_Longitude(Degrees)',
 'Site_Elevation(m)',
 'Solar_Zenith_Angle(Degrees)',
 'Optical_Air_Mass',
 'Sensor_Temperature(Degrees_C)',
 'Ozone(Dobson)',
 'NO2(Dobson)',
 'Last_Date_Processed',
 'Number_of_Wavelengths',
 'Exact_Wavelengths_of_AOD(um)_1640nm',
 'Exact_Wavelengths_of_AOD(um)_1020nm',
 'Exact_Wavelengths_of_AOD(um)_870nm',
 'Exact_Wavelengths_of_AOD(um)_865nm',
 'Exact_Wavelengths_of_AOD(um)_779nm',
 'Exact_Wavelengths_of_AOD(um)_675nm',
 'Exact_Wavelengths_of_AOD(um)_667nm',
 'Exact_Wavelengths_of_AOD(um)_620nm',
 'Exact_Wavelengths_of_AOD(um)_560nm',
 'Exact_Wavelengths_of_AOD(um)_555nm',
 'Exact_Wavelengths_of_AOD(um)_551nm',
 'Exact_Wavelengths_of_AOD(um)_532nm',
 'Exact_Wavelengths_of_AOD(um)_531nm',
 'Exact_Wavelengths_of_AOD(um)_510nm',
 'Exact_Wavelengths_of_AOD(um)_500nm',
 'Exact_Wavelengths_of_AOD(um)_490nm',
 'Exact_Wavelengths_of_AOD(um)_443nm',
 'Exact_Wavelengths_of_AOD(um)_440nm',
 'Exact_Wavelengths_of_AOD(um)_412nm',
 'Exact_Wavelengths_of_AOD(um)_400nm',
 'Exact_Wavelengths_of_AOD(um)_380nm',
 'Exact_Wavelengths_of_AOD(um)_340nm',
 'Exact_Wavelengths_of_PW(um)_935nm',
 'Exact_Wavelengths_of_AOD(um)_681nm',
 'Exact_Wavelengths_of_AOD(um)_709nm',
 'Exact_Wavelengths_of_AOD(um)_Empty',
 'Exact_Wavelengths_of_AOD(um)_Empty.1',
 'Exact_Wavelengths_of_AOD(um)_Empty.2',
 'Exact_Wavelengths_of_AOD(um)_Empty.3',
 'Exact_Wavelengths_of_AOD(um)_Empty.4']

In [67]:
aeronet["AOD_500nm"]

0       0.027484
1       0.027644
2       0.028083
3       0.028126
4       0.026957
          ...
1397    0.363963
1398    0.366079
1399    0.368987
1400    0.367249
1401    0.372124
Name: AOD_500nm, Length: 1402, dtype: float64

In [68]:
drops = list(aeronet.columns[20:])
print(drops)

['AOD_443nm', 'AOD_440nm', 'AOD_412nm', 'AOD_400nm', 'AOD_380nm', 'AOD_340nm', 'Precipitable_Water(cm)', 'AOD_681nm', 'AOD_709nm', 'AOD_Empty', 'AOD_Empty.1', 'AOD_Empty.2', 'AOD_Empty.3', 'AOD_Empty.4', 'Triplet_Variability_1640', 'Triplet_Variability_1020', 'Triplet_Variability_870', 'Triplet_Variability_865', 'Triplet_Variability_779', 'Triplet_Variability_675', 'Triplet_Variability_667', 'Triplet_Variability_620', 'Triplet_Variability_560', 'Triplet_Variability_555', 'Triplet_Variability_551', 'Triplet_Variability_532', 'Triplet_Variability_531', 'Triplet_Variability_510', 'Triplet_Variability_500', 'Triplet_Variability_490', 'Triplet_Variability_443', 'Triplet_Variability_440', 'Triplet_Variability_412', 'Triplet_Variability_400', 'Triplet_Variability_380', 'Triplet_Variability_340', 'Triplet_Variability_Precipitable_Water(cm)', 'Triplet_Variability_681', 'Triplet_Variability_709', 'Triplet_Variability_AOD_Empty', 'Triplet_Variability_AOD_Empty.1', 'Triplet_Variability_AOD_Empty.2', 'Triplet_Variability_AOD_Empty.3', 'Triplet_Variability_AOD_Empty.4', '440-870_Angstrom_Exponent', '380-500_Angstrom_Exponent', '440-675_Angstrom_Exponent', '500-870_Angstrom_Exponent', '340-440_Angstrom_Exponent', '440-675_Angstrom_Exponent[Polar]', 'Data_Quality_Level', 'AERONET_Instrument_Number', 'AERONET_Site_Name', 'Site_Latitude(Degrees)', 'Site_Longitude(Degrees)', 'Site_Elevation(m)', 'Solar_Zenith_Angle(Degrees)', 'Optical_Air_Mass', 'Sensor_Temperature(Degrees_C)', 'Ozone(Dobson)', 'NO2(Dobson)', 'Last_Date_Processed', 'Number_of_Wavelengths', 'Exact_Wavelengths_of_AOD(um)_1640nm', 'Exact_Wavelengths_of_AOD(um)_1020nm', 'Exact_Wavelengths_of_AOD(um)_870nm', 'Exact_Wavelengths_of_AOD(um)_865nm', 'Exact_Wavelengths_of_AOD(um)_779nm', 'Exact_Wavelengths_of_AOD(um)_675nm', 'Exact_Wavelengths_of_AOD(um)_667nm', 'Exact_Wavelengths_of_AOD(um)_620nm', 'Exact_Wavelengths_of_AOD(um)_560nm', 'Exact_Wavelengths_of_AOD(um)_555nm', 'Exact_Wavelengths_of_AOD(um)_551nm', 'Exact_Wavelengths_of_AOD(um)_532nm', 'Exact_Wavelengths_of_AOD(um)_531nm', 'Exact_Wavelengths_of_AOD(um)_510nm', 'Exact_Wavelengths_of_AOD(um)_500nm', 'Exact_Wavelengths_of_AOD(um)_490nm', 'Exact_Wavelengths_of_AOD(um)_443nm', 'Exact_Wavelengths_of_AOD(um)_440nm', 'Exact_Wavelengths_of_AOD(um)_412nm', 'Exact_Wavelengths_of_AOD(um)_400nm', 'Exact_Wavelengths_of_AOD(um)_380nm', 'Exact_Wavelengths_of_AOD(um)_340nm', 'Exact_Wavelengths_of_PW(um)_935nm', 'Exact_Wavelengths_of_AOD(um)_681nm', 'Exact_Wavelengths_of_AOD(um)_709nm', 'Exact_Wavelengths_of_AOD(um)_Empty', 'Exact_Wavelengths_of_AOD(um)_Empty.1', 'Exact_Wavelengths_of_AOD(um)_Empty.2', 'Exact_Wavelengths_of_AOD(um)_Empty.3', 'Exact_Wavelengths_of_AOD(um)_Empty.4']

In [69]:
aeronet_short = aeronet.drop(columns=drops)

In [70]:
aeronet_short.head()

,Date(dd:mm:yyyy),Time(hh:mm:ss),Day_of_Year,Day_of_Year(Fraction),AOD_1640nm,AOD_1020nm,AOD_870nm,AOD_865nm,AOD_779nm,AOD_675nm,AOD_667nm,AOD_620nm,AOD_560nm,AOD_555nm,AOD_551nm,AOD_532nm,AOD_531nm,AOD_510nm,AOD_500nm,AOD_490nm
0,01:01:2025,15:51:37,1,1.660845,0.006693,0.014841,0.017032,-999.0,-999.0,0.022185,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,0.027484,-999.0
1,01:01:2025,15:54:10,1,1.662616,0.006835,0.015043,0.016874,-999.0,-999.0,0.022377,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,0.027644,-999.0
2,01:01:2025,15:56:38,1,1.664329,0.006976,0.015269,0.017126,-999.0,-999.0,0.022490,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,0.028083,-999.0
3,01:01:2025,15:58:36,1,1.665694,0.007513,0.015661,0.017646,-999.0,-999.0,0.022898,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,0.028126,-999.0
4,01:01:2025,16:01:37,1,1.667789,0.006747,0.014947,0.017023,-999.0,-999.0,0.022029,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,0.026957,-999.0

In [71]:
header = None
data_rows = []

with open(aeronet_file) as data:
    for line_num, row in enumerate(data):
        if line_num < 6:  # Skip first 6 rows
            continue
        elif line_num == 6:  # Row 7 is the header
            header = row.strip().split(",")
        else:  # Data rows
            values = row.strip().split(",")
            data_rows.append(values)

# Convert to pandas DataFrame
aeronet_manual = pd.DataFrame(data_rows, columns=header)
print(aeronet_manual.head())

  Date(dd:mm:yyyy) Time(hh:mm:ss) Day_of_Year Day_of_Year(Fraction)  \
0       01:01:2025       15:51:37           1              1.660845
1       01:01:2025       15:54:10           1              1.662616
2       01:01:2025       15:56:38           1              1.664329
3       01:01:2025       15:58:36           1              1.665694
4       01:01:2025       16:01:37           1              1.667789

  AOD_1640nm AOD_1020nm AOD_870nm    AOD_865nm    AOD_779nm AOD_675nm  ...  \
0   0.006693   0.014841  0.017032  -999.000000  -999.000000  0.022185  ...
1   0.006835   0.015043  0.016874  -999.000000  -999.000000  0.022377  ...
2   0.006976   0.015269  0.017126  -999.000000  -999.000000  0.022490  ...
3   0.007513   0.015661  0.017646  -999.000000  -999.000000  0.022898  ...
4   0.006747   0.014947  0.017023  -999.000000  -999.000000  0.022029  ...

  Exact_Wavelengths_of_AOD(um)_380nm Exact_Wavelengths_of_AOD(um)_340nm  \
0                           0.379158                           0.339815
1                           0.379158                           0.339815
2                           0.379158                           0.339815
3                           0.379158                           0.339815
4                           0.379158                           0.339815

  Exact_Wavelengths_of_PW(um)_935nm Exact_Wavelengths_of_AOD(um)_681nm  \
0                          0.937502                              -999.
1                          0.937502                              -999.
2                          0.937502                              -999.
3                          0.937502                              -999.
4                          0.937502                              -999.

  Exact_Wavelengths_of_AOD(um)_709nm Exact_Wavelengths_of_AOD(um)_Empty  \
0                              -999.                              -999.
1                              -999.                              -999.
2                              -999.                              -999.
3                              -999.                              -999.
4                              -999.                              -999.

  Exact_Wavelengths_of_AOD(um)_Empty Exact_Wavelengths_of_AOD(um)_Empty  \
0                              -999.                              -999.
1                              -999.                              -999.
2                              -999.                              -999.
3                              -999.                              -999.
4                              -999.                              -999.

  Exact_Wavelengths_of_AOD(um)_Empty Exact_Wavelengths_of_AOD(um)_Empty
0                              -999.                              -999.
1                              -999.                              -999.
2                              -999.                              -999.
3                              -999.                              -999.
4                              -999.                              -999.

[5 rows x 113 columns]

## 5.2 NetCDF

In [73]:
filename = "JRR-AOD_v3r2_j01_s202306071807538_e202306071809183_c202306071842528.nc"
aod_file = Path("./data/aod") / filename
aod_nc = Dataset(aod_file)

In [74]:
print(aod_nc)

<class 'netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    Conventions: CF-1.6
    Metadata_Conventions: CF-1.6, Unidata Dataset Discovery v1.0
    standard_name_vocabulary: CF Standard Name Table v76
    institution: DOC/NOAA/NESDIS/NDE > S-NPP Data Exploitation, NESDIS, NOAA, U.S. Department of Commerce
    naming_authority: gov.noaa.nesdis.nde
    processing_level: NOAA Level 2
    production_site: NCCF
    production_environment: prod
    sensor_band_identifier: M1,M2,M3,M4,M5,M6,M7,M8,M9,M10,M11,M15,M16
    sensor_band_central_radiation_wavelength: 0.412um,0.445um,0.488um,0.555um,0.672um,0.746um,0.865um,1.240um,1.378um,1.610um,2.250um,10.76um,12.01um
    satellite_name: NOAA-20
    instrument_name: VIIRS
    project: JPSS Risk Reduction: Enterprise Aerosol Optical Depth/Particle Size Products
    summary: Enterprise Aerosol Optical Depth/ Aerosol Particle Size Products
    history: Enterprise Aerosol Optical Depth Algorithm v1.4.0
    references: N/A
    resolution: 750M
    time_coverage_start: 2023-06-07T18:07:53Z
    time_coverage_end: 2023-06-07T18:09:18Z
    date_created: 2023-06-07T18:42:52Z
    geospatial_lat_units: degrees_north
    geospatial_lon_units: degrees_east
    cdm_data_type: swath
    title: JRR-AOD
    Metadata_Link: JRR-AOD_v3r2_j01_s202306071807538_e202306071809183_c202306071842528.nc
    history_package: Delivery Package v3r2
    id: 0580d61b-1835-4703-8ab4-b4cffd317a19
    geospatial_bounds: POLYGON((-59.8867569 39.1987305, -93.4008636 34.1494904, -96.1057281 38.8374062, -60.1584473 44.2500839,-59.8867569 39.1987305))
    day_night_data_flag: day
    start_orbit_number: 28764
    end_orbit_number: 28764
    ascend_descend_data_flag: 0
    geospatial_first_scanline_first_fov_lat: 39.19873
    geospatial_first_scanline_last_fov_lat: 44.250084
    geospatial_last_scanline_first_fov_lat: 34.14949
    geospatial_last_scanline_last_fov_lat: 38.837406
    geospatial_first_scanline_first_fov_lon: -59.886757
    geospatial_first_scanline_last_fov_lon: -60.158447
    geospatial_last_scanline_first_fov_lon: -93.40086
    geospatial_last_scanline_last_fov_lon: -96.10573
    dimensions(sizes): Columns(3200), Rows(768), AbiAODnchn(11), LndLUTnchn(4)
    variables(dimensions): int32 StartRow(), int32 StartColumn(), float32 Latitude(Rows, Columns), float32 Longitude(Rows, Columns), int8 QCExtn(Rows, Columns), int8 QCTest(Rows, Columns), int8 QCInput(Rows, Columns), int8 QCPath(Rows, Columns), int8 QCRet(Rows, Columns), int8 QCAll(Rows, Columns), int8 QCAE(Rows, Columns), int8 FineMdlIdx(Rows, Columns), int8 CoarseMdlIdx(Rows, Columns), float32 FineModWgt(Rows, Columns), int8 AerMdl(Rows, Columns), float32 AOD550(Rows, Columns), float32 AOD_channel(Rows, Columns, AbiAODnchn), float32 AngsExp1(Rows, Columns), float32 AngsExp2(Rows, Columns), float32 SfcRefl(Rows, Columns, AbiAODnchn), float32 SpaStddev(Rows, Columns), float32 Residual(Rows, Columns), float32 AOD550LndMdl(Rows, Columns, LndLUTnchn), float32 ResLndMdl(Rows, Columns, LndLUTnchn), float32 HighQualityPct(), float32 RetrievalPct(), float32 MeanAOD(), float32 MeanAODHighQuality(), int64 cloud_mask_granule_level_quality_flag(), int8 CloudMaskQualFlag(Rows, Columns)
    groups:

In [75]:
aod_nc.variables.keys()

dict_keys(['StartRow', 'StartColumn', 'Latitude', 'Longitude', 'QCExtn', 'QCTest', 'QCInput', 'QCPath', 'QCRet', 'QCAll', 'QCAE', 'FineMdlIdx', 'CoarseMdlIdx', 'FineModWgt', 'AerMdl', 'AOD550', 'AOD_channel', 'AngsExp1', 'AngsExp2', 'SfcRefl', 'SpaStddev', 'Residual', 'AOD550LndMdl', 'ResLndMdl', 'HighQualityPct', 'RetrievalPct', 'MeanAOD', 'MeanAODHighQuality', 'cloud_mask_granule_level_quality_flag', 'CloudMaskQualFlag'])

In [76]:
AOD_550_nc = aod_nc.variables["AOD550"]
type(AOD_550_nc)

netCDF4._netCDF4.Variable

In [77]:
AOD_550 = np.array(AOD_550_nc[:,:], copy=True)
AOD_550.shape, type(AOD_550)

((768, 3200), numpy.ndarray)

In [78]:
AOD_550

array([[-9.9999902e+02, -9.9999902e+02, -9.9999902e+02, ...,
        -9.9999902e+02, -9.9999902e+02, -9.9999902e+02],
       [-9.9999902e+02, -9.9999902e+02, -9.9999902e+02, ...,
        -9.9999902e+02, -9.9999902e+02, -9.9999902e+02],
       [ 1.1380934e+00,  1.1309069e+00,  1.1342988e+00, ...,
        -9.9999902e+02, -9.9999902e+02, -9.9999902e+02],
       ...,
       [ 2.3103447e+00,  2.2670970e+00,  2.1457357e+00, ...,
         1.6736546e-01,  1.6509396e-01,  2.1845175e-01],
       [-9.9999902e+02, -9.9999902e+02, -9.9999902e+02, ...,
        -9.9999902e+02, -9.9999902e+02, -9.9999902e+02],
       [-9.9999902e+02, -9.9999902e+02, -9.9999902e+02, ...,
        -9.9999902e+02, -9.9999902e+02, -9.9999902e+02]], dtype=float32)

In [79]:
avg_AOD = AOD_550.mean()
print(avg_AOD)

-490.58963

In [80]:
print(aod_nc.variables["AOD550"])

<class 'netCDF4.Variable'>
float32 AOD550(Rows, Columns)
    long_name: AOT at 0.55 micron for both ocean and land
    coordinates: Longitude Latitude
    _FillValue: -999.999
    valid_range: [-0.05  5.  ]
    units: 1
unlimited dimensions:
current shape = (768, 3200)
filling on

In [81]:
AOD_MISSING = aod_nc.variables["AOD550"]._FillValue
AOD_MISSING

-999.999

In [82]:
keep_rows = AOD_550 != AOD_MISSING

AOD_550[50:60, 100], keep_rows[50:60, 100]

(array([-999.999, -999.999, -999.999, -999.999, -999.999, -999.999,
        -999.999, -999.999, -999.999, -999.999], dtype=float32),
 array([False, False, False, False, False, False, False, False, False,
        False]))

In [83]:
AOD_550_filtered = AOD_550[keep_rows]
AOD_550_filtered

array([0.7885785 , 0.7921825 , 0.7922244 , ..., 0.71011645, 0.79880345,
       0.7597933 ], dtype=float32)

In [84]:
# Re-compute the statistics, these values look more reasonable.
avg_AOD_filtered = AOD_550_filtered.mean()
avg_AOD_filtered

1.3899387

In [85]:
AOD_550.size, AOD_550_filtered.size

(2457600, 1250188)

In [86]:
AOD_550_ma = aod_nc.variables["AOD550"][:,:]
type(AOD_550_ma)

numpy.ma.MaskedArray

In [87]:
AOD_550_ma[50:60, 100]

masked_array(data=[--, --, --, --, --, --, --, --, --, --],
             mask=[ True,  True,  True,  True,  True,  True,  True,  True,
                    True,  True],
       fill_value=-999.999,
            dtype=float32)

In [88]:
avg_AOD_ma = AOD_550_ma.mean()
avg_AOD_ma

1.389938753211517

In [89]:
aod_nc.variables["AOD550"].valid_range

array([-0.05,  5.  ], dtype=float32)

## 5.3 HDF

In [ ]:
filename = "3B-HHR.MS.MRG.3IMERG.20240927-S073000-E075959.0450.V07B.HDF5"
imerg_file = Path("./data/imerg") / filename
imerg_h5 = h5py.File(imerg_file, "r")
imerg_h5

In [91]:
list(imerg_h5)

['Grid']

In [92]:
print(list(imerg_h5["Grid"].keys()))

['Intermediate', 'nv', 'lonv', 'latv', 'time', 'lon', 'lat', 'time_bnds', 'lon_bnds', 'lat_bnds', 'precipitation', 'randomError', 'probabilityLiquidPrecipitation', 'precipitationQualityIndex']

In [93]:
imerg_h5.visit(print)

Grid
Grid/Intermediate
Grid/Intermediate/IRinfluence
Grid/Intermediate/IRprecipitation
Grid/Intermediate/MWobservationTime
Grid/Intermediate/MWprecipSource
Grid/Intermediate/MWprecipitation
Grid/Intermediate/precipitationUncal
Grid/lat
Grid/lat_bnds
Grid/latv
Grid/lon
Grid/lon_bnds
Grid/lonv
Grid/nv
Grid/precipitation
Grid/precipitationQualityIndex
Grid/probabilityLiquidPrecipitation
Grid/randomError
Grid/time
Grid/time_bnds

In [94]:
precip = imerg_h5["Grid/precipitation"][:,:,:]
precip

array([[[    0. ,     0. ,     0. , ...,     0. , -9999.9, -9999.9],
        [    0. ,     0. ,     0. , ...,     0. , -9999.9, -9999.9],
        [    0. ,     0. ,     0. , ...,     0. , -9999.9, -9999.9],
        ...,
        [    0. ,     0. ,     0. , ...,     0. , -9999.9, -9999.9],
        [    0. ,     0. ,     0. , ...,     0. , -9999.9, -9999.9],
        [    0. ,     0. ,     0. , ...,     0. , -9999.9, -9999.9]]],
      dtype=float32)

In [95]:
print(list(imerg_h5["Grid/precipitation"].attrs))

['DimensionNames', 'Units', 'units', 'coordinates', '_FillValue', 'CodeMissingValue', 'LongName', 'DIMENSION_LIST']

In [96]:
PRECIP_MISSING = imerg_h5["Grid/precipitation"].attrs["_FillValue"]
PRECIP_MISSING

-9999.9

In [97]:
precip_mask = (precip == PRECIP_MISSING)
precip_filtered = np.ma.masked_array(precip, mask=precip_mask)
precip_filtered

masked_array(
  data=[[[0.0, 0.0, 0.0, ..., 0.0, --, --],
         [0.0, 0.0, 0.0, ..., 0.0, --, --],
         [0.0, 0.0, 0.0, ..., 0.0, --, --],
         ...,
         [0.0, 0.0, 0.0, ..., 0.0, --, --],
         [0.0, 0.0, 0.0, ..., 0.0, --, --],
         [0.0, 0.0, 0.0, ..., 0.0, --, --]]],
  mask=[[[False, False, False, ..., False,  True,  True],
         [False, False, False, ..., False,  True,  True],
         [False, False, False, ..., False,  True,  True],
         ...,
         [False, False, False, ..., False,  True,  True],
         [False, False, False, ..., False,  True,  True],
         [False, False, False, ..., False,  True,  True]]],
  fill_value=1e+20,
  dtype=float32)

In [98]:
precip_filtered.mean()

0.09429218143186643

## 5.4 GRIB2

In [ ]:
filename = "gfs.t00z.pgrb2.1p00.anl"
gfs_file = Path("./data/gfs") / filename
gfs_grb2 = pygrib.open(gfs_file)
records = [str(grb) for grb in gfs_grb2]

In [101]:
records[511]

'512:Temperature:K (instant):regular_ll:isobaricInhPa:level 100000 Pa:fcst time 0 hrs:from 202601170000'

In [102]:
gfs_temps = gfs_grb2.select(name="Temperature")
gfs_temps

[8:Temperature:K (instant):regular_ll:isobaricInPa:level 1 Pa:fcst time 0 hrs:from 202601170000,
 18:Temperature:K (instant):regular_ll:isobaricInPa:level 2 Pa:fcst time 0 hrs:from 202601170000,
 28:Temperature:K (instant):regular_ll:isobaricInPa:level 4 Pa:fcst time 0 hrs:from 202601170000,
 38:Temperature:K (instant):regular_ll:isobaricInPa:level 7 Pa:fcst time 0 hrs:from 202601170000,
 48:Temperature:K (instant):regular_ll:isobaricInPa:level 10 Pa:fcst time 0 hrs:from 202601170000,
 58:Temperature:K (instant):regular_ll:isobaricInPa:level 20 Pa:fcst time 0 hrs:from 202601170000,
 68:Temperature:K (instant):regular_ll:isobaricInPa:level 40 Pa:fcst time 0 hrs:from 202601170000,
 78:Temperature:K (instant):regular_ll:isobaricInPa:level 70 Pa:fcst time 0 hrs:from 202601170000,
 88:Temperature:K (instant):regular_ll:isobaricInhPa:level 100 Pa:fcst time 0 hrs:from 202601170000,
 98:Temperature:K (instant):regular_ll:isobaricInhPa:level 200 Pa:fcst time 0 hrs:from 202601170000,
 108:Temperature:K (instant):regular_ll:isobaricInhPa:level 300 Pa:fcst time 0 hrs:from 202601170000,
 118:Temperature:K (instant):regular_ll:isobaricInhPa:level 500 Pa:fcst time 0 hrs:from 202601170000,
 128:Temperature:K (instant):regular_ll:isobaricInhPa:level 700 Pa:fcst time 0 hrs:from 202601170000,
 138:Temperature:K (instant):regular_ll:isobaricInhPa:level 1000 Pa:fcst time 0 hrs:from 202601170000,
 148:Temperature:K (instant):regular_ll:isobaricInhPa:level 1500 Pa:fcst time 0 hrs:from 202601170000,
 158:Temperature:K (instant):regular_ll:isobaricInhPa:level 2000 Pa:fcst time 0 hrs:from 202601170000,
 168:Temperature:K (instant):regular_ll:isobaricInhPa:level 3000 Pa:fcst time 0 hrs:from 202601170000,
 178:Temperature:K (instant):regular_ll:isobaricInhPa:level 4000 Pa:fcst time 0 hrs:from 202601170000,
 188:Temperature:K (instant):regular_ll:isobaricInhPa:level 5000 Pa:fcst time 0 hrs:from 202601170000,
 203:Temperature:K (instant):regular_ll:isobaricInhPa:level 7000 Pa:fcst time 0 hrs:from 202601170000,
 213:Temperature:K (instant):regular_ll:isobaricInhPa:level 10000 Pa:fcst time 0 hrs:from 202601170000,
 228:Temperature:K (instant):regular_ll:isobaricInhPa:level 15000 Pa:fcst time 0 hrs:from 202601170000,
 243:Temperature:K (instant):regular_ll:isobaricInhPa:level 20000 Pa:fcst time 0 hrs:from 202601170000,
 258:Temperature:K (instant):regular_ll:isobaricInhPa:level 25000 Pa:fcst time 0 hrs:from 202601170000,
 273:Temperature:K (instant):regular_ll:isobaricInhPa:level 30000 Pa:fcst time 0 hrs:from 202601170000,
 288:Temperature:K (instant):regular_ll:isobaricInhPa:level 35000 Pa:fcst time 0 hrs:from 202601170000,
 303:Temperature:K (instant):regular_ll:isobaricInhPa:level 40000 Pa:fcst time 0 hrs:from 202601170000,
 318:Temperature:K (instant):regular_ll:isobaricInhPa:level 45000 Pa:fcst time 0 hrs:from 202601170000,
 333:Temperature:K (instant):regular_ll:isobaricInhPa:level 50000 Pa:fcst time 0 hrs:from 202601170000,
 348:Temperature:K (instant):regular_ll:isobaricInhPa:level 55000 Pa:fcst time 0 hrs:from 202601170000,
 363:Temperature:K (instant):regular_ll:isobaricInhPa:level 60000 Pa:fcst time 0 hrs:from 202601170000,
 378:Temperature:K (instant):regular_ll:isobaricInhPa:level 65000 Pa:fcst time 0 hrs:from 202601170000,
 393:Temperature:K (instant):regular_ll:isobaricInhPa:level 70000 Pa:fcst time 0 hrs:from 202601170000,
 408:Temperature:K (instant):regular_ll:isobaricInhPa:level 75000 Pa:fcst time 0 hrs:from 202601170000,
 423:Temperature:K (instant):regular_ll:isobaricInhPa:level 80000 Pa:fcst time 0 hrs:from 202601170000,
 438:Temperature:K (instant):regular_ll:isobaricInhPa:level 85000 Pa:fcst time 0 hrs:from 202601170000,
 453:Temperature:K (instant):regular_ll:isobaricInhPa:level 90000 Pa:fcst time 0 hrs:from 202601170000,
 468:Temperature:K (instant):regular_ll:isobaricInhPa:level 92500 Pa:fcst time 0 hrs:from 202601170000,
 483:Temperature:K (instant):regular_ll:isobaricInhPa:level 95000 Pa:fcst time 0 hrs:from 202601170000,
 498:Temperature:K (instant):regular_ll:isobaricInhPa:level 97500 Pa:fcst time 0 hrs:from 202601170000,
 512:Temperature:K (instant):regular_ll:isobaricInhPa:level 100000 Pa:fcst time 0 hrs:from 202601170000,
 543:Temperature:K (instant):regular_ll:tropopause:level 0:fcst time 0 hrs:from 202601170000,
 552:Temperature:K (instant):regular_ll:maxWind:level 0:fcst time 0 hrs:from 202601170000,
 561:Temperature:K (instant):regular_ll:heightAboveGround:level 80 m:fcst time 0 hrs:from 202601170000,
 564:Temperature:K (instant):regular_ll:heightAboveGround:level 100 m:fcst time 0 hrs:from 202601170000,
 567:Temperature:K (instant):regular_ll:heightAboveSea:level 1829 m:fcst time 0 hrs:from 202601170000,
 570:Temperature:K (instant):regular_ll:heightAboveSea:level 2743 m:fcst time 0 hrs:from 202601170000,
 573:Temperature:K (instant):regular_ll:heightAboveSea:level 3658 m:fcst time 0 hrs:from 202601170000,
 580:Temperature:K (instant):regular_ll:pressureFromGroundLayer:levels 3000-0 Pa:fcst time 0 hrs:from 202601170000,
 592:Temperature:K (instant):regular_ll:sigma:level 0.995 sigma value:fcst time 0 hrs:from 202601170000,
 601:Temperature:K (instant):regular_ll:potentialVorticity:level 2e-06 K m2 kg-1 s-1:fcst time 0 hrs:from 202601170000,
 607:Temperature:K (instant):regular_ll:potentialVorticity:level -2.147481648 K m2 kg-1 s-1:fcst time 0 hrs:from 202601170000]

In [103]:
gfs_temp = gfs_grb2[437]

In [104]:
gfs_temp.keys()

['globalDomain',
 'GRIBEditionNumber',
 'tablesVersionLatestOfficial',
 'tablesVersionLatest',
 'grib2divider',
 'angleSubdivisions',
 'missingValue',
 'ieeeFloats',
 'isHindcast',
 'section0Length',
 'identifier',
 'discipline',
 'editionNumber',
 'totalLength',
 'sectionNumber',
 'section1Length',
 'numberOfSection',
 'centre',
 'centreDescription',
 'subCentre',
 'tablesVersion',
 'masterDir',
 'localTablesVersion',
 'significanceOfReferenceTime',
 'year',
 'month',
 'day',
 'hour',
 'minute',
 'second',
 'dataDate',
 'julianDay',
 'dataTime',
 'productionStatusOfProcessedData',
 'typeOfProcessedData',
 'md5Section1',
 'selectStepTemplateInterval',
 'selectStepTemplateInstant',
 'stepType',
 'is_chemical',
 'is_chemical_distfn',
 'is_chemical_srcsink',
 'is_aerosol',
 'is_aerosol_optical',
 'is_probability_fcst',
 'is_wave_period_range',
 'setCalendarId',
 'deleteCalendarId',
 'conceptsDir1',
 'conceptsDir2',
 'eps',
 'sectionNumber',
 'grib2LocalSectionPresent',
 'deleteLocalDefinition',
 'sectionNumber',
 'gridDescriptionSectionPresent',
 'section3Length',
 'numberOfSection',
 'sourceOfGridDefinition',
 'numberOfDataPoints',
 'numberOfOctectsForNumberOfPoints',
 'interpretationOfNumberOfPoints',
 'PLPresent',
 'gridDefinitionTemplateNumber',
 'gridDefinitionDescription',
 'shapeOfTheEarth',
 'scaleFactorOfRadiusOfSphericalEarth',
 'scaledValueOfRadiusOfSphericalEarth',
 'scaleFactorOfEarthMajorAxis',
 'scaledValueOfEarthMajorAxis',
 'scaleFactorOfEarthMinorAxis',
 'scaledValueOfEarthMinorAxis',
 'radius',
 'isGridded',
 'Ni',
 'Nj',
 'basicAngleOfTheInitialProductionDomain',
 'mBasicAngle',
 'angleMultiplier',
 'mAngleMultiplier',
 'subdivisionsOfBasicAngle',
 'angleDivisor',
 'latitudeOfFirstGridPoint',
 'longitudeOfFirstGridPoint',
 'resolutionAndComponentFlags',
 'resolutionAndComponentFlags1',
 'resolutionAndComponentFlags2',
 'iDirectionIncrementGiven',
 'jDirectionIncrementGiven',
 'uvRelativeToGrid',
 'resolutionAndComponentFlags6',
 'resolutionAndComponentFlags7',
 'resolutionAndComponentFlags8',
 'ijDirectionIncrementGiven',
 'latitudeOfLastGridPoint',
 'longitudeOfLastGridPoint',
 'iDirectionIncrement',
 'jDirectionIncrement',
 'scanningMode',
 'iScansNegatively',
 'jScansPositively',
 'jPointsAreConsecutive',
 'alternativeRowScanning',
 'iScansPositively',
 'jScansNegatively',
 'scanningMode5',
 'scanningMode6',
 'scanningMode7',
 'scanningMode8',
 'g2grid',
 'latitudeOfFirstGridPointInDegrees',
 'longitudeOfFirstGridPointInDegrees',
 'latitudeOfLastGridPointInDegrees',
 'longitudeOfLastGridPointInDegrees',
 'iDirectionIncrementInDegrees',
 'jDirectionIncrementInDegrees',
 'latLonValues',
 'latitudes',
 'longitudes',
 'distinctLatitudes',
 'distinctLongitudes',
 'gridType',
 'md5Section3',
 'isSpectral',
 'sectionNumber',
 'section4Length',
 'numberOfSection',
 'NV',
 'neitherPresent',
 'datasetForLocal',
 'productDefinitionTemplateNumber',
 'genVertHeightCoords',
 'parameterCategory',
 'parameterNumber',
 'parameterUnits',
 'parameterName',
 'typeOfGeneratingProcess',
 'backgroundProcess',
 'generatingProcessIdentifier',
 'hoursAfterDataCutoff',
 'minutesAfterDataCutoff',
 'indicatorOfUnitForForecastTime',
 'stepUnits',
 'forecastTime',
 'startStep',
 'endStep',
 'stepRange',
 'stepTypeInternal',
 'validityDate',
 'validityTime',
 'validityDateTime',
 'typeOfFirstFixedSurface',
 'unitsOfFirstFixedSurface',
 'nameOfFirstFixedSurface',
 'scaleFactorOfFirstFixedSurface',
 'scaledValueOfFirstFixedSurface',
 'typeOfSecondFixedSurface',
 'unitsOfSecondFixedSurface',
 'nameOfSecondFixedSurface',
 'scaleFactorOfSecondFixedSurface',
 'scaledValueOfSecondFixedSurface',
 'pressureUnits',
 'typeOfLevel',
 'level',
 'bottomLevel',
 'topLevel',
 'levtype',
 'tempPressureUnits',
 'productDefinitionTemplateName',
 'enableChemSplit',
 'paramIdECMF',
 'paramId',
 'shortNameECMF',
 'shortName',
 'unitsECMF',
 'units',
 'nameECMF',
 'name',
 'cfNameECMF',
 'cfName',
 'cfVarName',
 'PVPresent',
 'deletePV',
 'timeSpan',
 'md5Section4',
 'lengthOfHeaders',
 'md5Headers',
 'sectionNumber',
 'section5Length',
 'numberOfSection',
 'numberOfValues',
 'dataRepresentationTemplateNumber',
 'packingType',
 'referenceValue',
 'referenceValueError',
 'binaryScaleFactor',
 'decimalScaleFactor',
 'optimizeScaleFactor',
 'bitsPerValue',
 'typeOfOriginalFieldValues',
 'groupSplittingMethodUsed',
 'missingValueManagementUsed',
 'primaryMissingValueSubstitute',
 'secondaryMissingValueSubstitute',
 'numberOfGroupsOfDataValues',
 'referenceForGroupWidths',
 'numberOfBitsUsedForTheGroupWidths',
 'referenceForGroupLengths',
 'lengthIncrementForTheGroupLengths',
 'trueLengthOfLastGroup',
 'numberOfBitsForScaledGroupLengths',
 'orderOfSpatialDifferencing',
 'numberOfOctetsExtraDescriptors',
 'md5Section5',
 'sectionNumber',
 'section6Length',
 'numberOfSection',
 'bitMapIndicator',
 'bitmapPresent',
 'missingValuesPresent',
 'md5Section6',
 'sectionNumber',
 'section7Length',
 'numberOfSection',
 'codedValues',
 'values',
 'maximum',
 'minimum',
 'average',
 'standardDeviation',
 'skewness',
 'kurtosis',
 'isConstant',
 'numberOfMissing',
 'changeDecimalPrecision',
 'decimalPrecision',
 'setBitsPerValue',
 'setPackingType',
 'getNumberOfValues',
 'scaleValuesBy',
 'offsetValuesBy',
 'productType',
 'md5Section7',
 'isMessageValid',
 'section8Length',
 'isTemplateDeprecated',
 'isTemplateExperimental',
 'paramIdForConversion',
 'analDate',
 'validDate']

In [105]:
gfs_lat = gfs_temp.latitudes
gfs_lon = gfs_temp.longitudes
gfs_level = gfs_temp.level
gfs_units = gfs_temp.units
gfs_analysis_date = gfs_temp.analDate
gfs_fcst_time = gfs_temp.forecastTime

## 5.5 Importing Data using xarray
### 5.5.1 netCDF

In [107]:
filename = "NUCAPS-EDR_v3r2_j01_s202501092048589_e202501092049287_c202501092139200.nc"
nucaps_file = Path("data/nucaps") / filename
nucaps = xr.open_dataset(nucaps_file, engine="h5netcdf")
print(nucaps)

<xarray.Dataset> Size: 4MB
Dimensions:                          (Number_of_CrIS_FORs: 120,
                                      Number_of_Ispares: 129,
                                      Number_of_Rspares: 298,
                                      Number_of_Cloud_Layers: 8,
                                      Number_of_P_Levels: 100,
                                      Number_of_MW_Spectral_Pts: 16,
                                      ...
                                      SO2_Function_Pres_X: 5,
                                      SO2_Function_Pres_Y: 5,
                                      SO2_Function_Idx: 6,
                                      HNO3_Function_Pres_X: 8,
                                      HNO3_Function_Pres_Y: 8,
                                      HNO3_Function_Idx: 9)
Coordinates:
    Time                             (Number_of_CrIS_FORs) datetime64[ns] 960B ...
    Latitude                         (Number_of_CrIS_FORs) float32 480B ...
    Longitude                        (Number_of_CrIS_FORs) float32 480B ...
    Pressure                         (Number_of_CrIS_FORs, Number_of_P_Levels) float32 48kB ...
    Effective_Pressure               (Number_of_CrIS_FORs, Number_of_P_Levels) float32 48kB ...
Dimensions without coordinates: Number_of_CrIS_FORs, Number_of_Ispares,
                                Number_of_Rspares, Number_of_Cloud_Layers,
                                Number_of_P_Levels, Number_of_MW_Spectral_Pts,
                                Number_of_Surf_Emis_Hinge_Pts,
                                Number_of_Stability_Parameters,
                                Number_of_Cloud_Emis_Hing_Pts,
                                ...
                                CH4_Function_Pres_X, CH4_Function_Pres_Y,
                                CH4_Function_Idx, CO2_Function_Pres_X,
                                CO2_Function_Pres_Y, CO2_Function_Idx,
                                SO2_Function_Pres_X, SO2_Function_Pres_Y,
                                SO2_Function_Idx, HNO3_Function_Pres_X,
                                HNO3_Function_Pres_Y, HNO3_Function_Idx
Data variables: (12/112)
    quality_information              |S1 1B ...
    CrIS_FORs                        (Number_of_CrIS_FORs) float64 960B ...
    View_Angle                       (Number_of_CrIS_FORs) float32 480B ...
    Satellite_Height                 (Number_of_CrIS_FORs) float32 480B ...
    FG_Mean_CO2                      (Number_of_CrIS_FORs) float32 480B ...
    Mean_CO2                         (Number_of_CrIS_FORs) float32 480B ...
    ...                               ...
    HNO3_AK                          (Number_of_CrIS_FORs, HNO3_Function_Pres_X, HNO3_Function_Pres_Y) float32 31kB ...
    HNO3_AK_Eff_Pressure             (Number_of_CrIS_FORs, HNO3_Function_Pres_X) float32 4kB ...
    HNO3_Function_Index              (HNO3_Function_Idx) float32 36B ...
    HNO3_Function_Last_Index         (Number_of_CrIS_FORs) float32 480B ...
    HNO3_Function_HTop               int16 2B ...
    HNO3_Function_HBot               int16 2B ...
Attributes: (12/51)
    Conventions:                              CF-1.8
    Metadata_Conventions:                     CF-1.8, Unidata Dataset Discove...
    standard_name_vocabulary:                 CF Standard Name Table (version...
    project:                                  NESDIS Common Cloud Framework
    title:                                    NUCAPS_EDR
    summary:                                  NUCAPS retrieved profiles of te...
    ...                                       ...
    geospatial_last_scanline_first_fov_lon:   -128.11
    geospatial_last_scanline_last_fov_lon:    -106.31
    geospatial_bounds:                        POLYGON((-128.21 30.22, -119.89...
    instrument_resolution:                    CrIS 2211 channels
    retrieval_mode:                           IR+MW
    number_valid_fovs:                        9

In [108]:
nucaps_profile = nucaps.sel(Number_of_CrIS_FORs=0)
print(nucaps_profile)

<xarray.Dataset> Size: 31kB
Dimensions:                          (Number_of_Ispares: 129,
                                      Number_of_Rspares: 298,
                                      Number_of_Cloud_Layers: 8,
                                      Number_of_P_Levels: 100,
                                      Number_of_MW_Spectral_Pts: 16,
                                      Number_of_Surf_Emis_Hinge_Pts: 100,
                                      ...
                                      SO2_Function_Pres_X: 5,
                                      SO2_Function_Pres_Y: 5,
                                      SO2_Function_Idx: 6,
                                      HNO3_Function_Pres_X: 8,
                                      HNO3_Function_Pres_Y: 8,
                                      HNO3_Function_Idx: 9)
Coordinates:
    Time                             datetime64[ns] 8B ...
    Latitude                         float32 4B ...
    Longitude                        float32 4B ...
    Pressure                         (Number_of_P_Levels) float32 400B ...
    Effective_Pressure               (Number_of_P_Levels) float32 400B ...
Dimensions without coordinates: Number_of_Ispares, Number_of_Rspares,
                                Number_of_Cloud_Layers, Number_of_P_Levels,
                                Number_of_MW_Spectral_Pts,
                                Number_of_Surf_Emis_Hinge_Pts,
                                Number_of_Stability_Parameters,
                                Number_of_Cloud_Emis_Hing_Pts,
                                ...
                                CH4_Function_Pres_X, CH4_Function_Pres_Y,
                                CH4_Function_Idx, CO2_Function_Pres_X,
                                CO2_Function_Pres_Y, CO2_Function_Idx,
                                SO2_Function_Pres_X, SO2_Function_Pres_Y,
                                SO2_Function_Idx, HNO3_Function_Pres_X,
                                HNO3_Function_Pres_Y, HNO3_Function_Idx
Data variables: (12/112)
    quality_information              |S1 1B ...
    CrIS_FORs                        float64 8B ...
    View_Angle                       float32 4B ...
    Satellite_Height                 float32 4B ...
    FG_Mean_CO2                      float32 4B ...
    Mean_CO2                         float32 4B ...
    ...                               ...
    HNO3_AK                          (HNO3_Function_Pres_X, HNO3_Function_Pres_Y) float32 256B ...
    HNO3_AK_Eff_Pressure             (HNO3_Function_Pres_X) float32 32B ...
    HNO3_Function_Index              (HNO3_Function_Idx) float32 36B ...
    HNO3_Function_Last_Index         float32 4B ...
    HNO3_Function_HTop               int16 2B ...
    HNO3_Function_HBot               int16 2B ...
Attributes: (12/51)
    Conventions:                              CF-1.8
    Metadata_Conventions:                     CF-1.8, Unidata Dataset Discove...
    standard_name_vocabulary:                 CF Standard Name Table (version...
    project:                                  NESDIS Common Cloud Framework
    title:                                    NUCAPS_EDR
    summary:                                  NUCAPS retrieved profiles of te...
    ...                                       ...
    geospatial_last_scanline_first_fov_lon:   -128.11
    geospatial_last_scanline_last_fov_lon:    -106.31
    geospatial_bounds:                        POLYGON((-128.21 30.22, -119.89...
    instrument_resolution:                    CrIS 2211 channels
    retrieval_mode:                           IR+MW
    number_valid_fovs:                        9

In [109]:
nucaps_temp_profile = nucaps_profile.Temperature
print(nucaps_temp_profile)

<xarray.DataArray 'Temperature' (Number_of_P_Levels: 100)> Size: 400B
[100 values with dtype=float32]
Coordinates:
    Time                datetime64[ns] 8B ...
    Latitude            float32 4B ...
    Longitude           float32 4B ...
    Pressure            (Number_of_P_Levels) float32 400B ...
    Effective_Pressure  (Number_of_P_Levels) float32 400B ...
Dimensions without coordinates: Number_of_P_Levels
Attributes:
    long_name:       Temperature
    standard_name:   air_temperature
    units:           Kelvin
    parameter_type:  NUCAPS data
    valid_range:     [   0. 1000.]

In [110]:
nucaps_lat, nucaps_lon = nucaps_profile.Latitude.item(), nucaps_profile.Longitude.item()
print(nucaps_lat, nucaps_lon)

30.37908935546875 -127.484619140625

In [111]:
nucaps_mask = nucaps_profile.Pressure.round() == 300
nucaps_gradient = nucaps.sel(Number_of_P_Levels = nucaps_mask)
print(nucaps_gradient)

<xarray.Dataset> Size: 2MB
Dimensions:                          (Number_of_CrIS_FORs: 120,
                                      Number_of_Ispares: 129,
                                      Number_of_Rspares: 298,
                                      Number_of_Cloud_Layers: 8,
                                      Number_of_P_Levels: 1,
                                      Number_of_MW_Spectral_Pts: 16,
                                      ...
                                      SO2_Function_Pres_X: 5,
                                      SO2_Function_Pres_Y: 5,
                                      SO2_Function_Idx: 6,
                                      HNO3_Function_Pres_X: 8,
                                      HNO3_Function_Pres_Y: 8,
                                      HNO3_Function_Idx: 9)
Coordinates:
    Time                             (Number_of_CrIS_FORs) datetime64[ns] 960B ...
    Latitude                         (Number_of_CrIS_FORs) float32 480B ...
    Longitude                        (Number_of_CrIS_FORs) float32 480B ...
    Pressure                         (Number_of_CrIS_FORs, Number_of_P_Levels) float32 480B ...
    Effective_Pressure               (Number_of_CrIS_FORs, Number_of_P_Levels) float32 480B ...
Dimensions without coordinates: Number_of_CrIS_FORs, Number_of_Ispares,
                                Number_of_Rspares, Number_of_Cloud_Layers,
                                Number_of_P_Levels, Number_of_MW_Spectral_Pts,
                                Number_of_Surf_Emis_Hinge_Pts,
                                Number_of_Stability_Parameters,
                                Number_of_Cloud_Emis_Hing_Pts,
                                ...
                                CH4_Function_Pres_X, CH4_Function_Pres_Y,
                                CH4_Function_Idx, CO2_Function_Pres_X,
                                CO2_Function_Pres_Y, CO2_Function_Idx,
                                SO2_Function_Pres_X, SO2_Function_Pres_Y,
                                SO2_Function_Idx, HNO3_Function_Pres_X,
                                HNO3_Function_Pres_Y, HNO3_Function_Idx
Data variables: (12/112)
    quality_information              |S1 1B ...
    CrIS_FORs                        (Number_of_CrIS_FORs) float64 960B ...
    View_Angle                       (Number_of_CrIS_FORs) float32 480B ...
    Satellite_Height                 (Number_of_CrIS_FORs) float32 480B ...
    FG_Mean_CO2                      (Number_of_CrIS_FORs) float32 480B ...
    Mean_CO2                         (Number_of_CrIS_FORs) float32 480B ...
    ...                               ...
    HNO3_AK                          (Number_of_CrIS_FORs, HNO3_Function_Pres_X, HNO3_Function_Pres_Y) float32 31kB ...
    HNO3_AK_Eff_Pressure             (Number_of_CrIS_FORs, HNO3_Function_Pres_X) float32 4kB ...
    HNO3_Function_Index              (HNO3_Function_Idx) float32 36B ...
    HNO3_Function_Last_Index         (Number_of_CrIS_FORs) float32 480B ...
    HNO3_Function_HTop               int16 2B ...
    HNO3_Function_HBot               int16 2B ...
Attributes: (12/51)
    Conventions:                              CF-1.8
    Metadata_Conventions:                     CF-1.8, Unidata Dataset Discove...
    standard_name_vocabulary:                 CF Standard Name Table (version...
    project:                                  NESDIS Common Cloud Framework
    title:                                    NUCAPS_EDR
    summary:                                  NUCAPS retrieved profiles of te...
    ...                                       ...
    geospatial_last_scanline_first_fov_lon:   -128.11
    geospatial_last_scanline_last_fov_lon:    -106.31
    geospatial_bounds:                        POLYGON((-128.21 30.22, -119.89...
    instrument_resolution:                    CrIS 2211 channels
    retrieval_mode:                           IR+MW
    number_valid_fovs:                        9

In [112]:
pres_dict = {}
for i, p in enumerate(nucaps_profile.Pressure):
    if p >= 100:
        pres_dict.update({int(p): i})

In [113]:
pres_dict[300]

62

In [114]:
mask = (nucaps.Pressure.round() == 300)
nucaps.Temperature.values[mask]

array([234.48776, 234.38278, 234.87227, 234.66133, 233.92627, 233.89029,
       233.86803, 233.47919, 232.8442 , 232.6856 , 232.08095, 232.18433,
       231.59848, 231.18376, 231.54617, 230.76129, 231.25395, 231.00624,
       231.32657, 231.6082 , 232.21297, 234.0453 , 234.71642, 235.09001,
       235.25209, 235.17984, 234.57895, 233.18793, 231.8072 , 230.0995 ,
       234.69618, 234.6436 , 234.34409, 234.03006, 234.01903, 234.19974,
       233.81705, 233.52342, 233.13332, 232.92628, 232.64357, 232.11537,
       232.08766, 231.40852, 231.3211 , 230.73827, 231.96568, 230.9996 ,
       231.18646, 231.34116, 231.7555 , 232.86064, 234.11073, 235.29643,
       235.48697, 234.67145, 234.4193 , 233.67233, 229.05916, 229.8415 ,
       234.40875, 234.39656, 234.94374, 234.22319, 234.06755, 234.40775,
       233.87978, 233.47063, 232.9242 , 232.57118, 232.34843, 232.13393,
       231.80893, 232.73764, 231.27658, 230.21349, 232.10675, 231.71501,
       231.26076, 230.90872, 230.59914, 232.47707, 233.85434, 234.69191,
       235.95175, 235.64131, 233.72018, 231.6125 , 230.5559 , 228.69566,
       234.80815, 233.7915 , 234.38712, 234.4202 , 234.14253, 233.86269,
       233.82187, 233.35968, 232.97859, 232.92545, 232.23055, 231.36118,
       231.80008, 231.53745, 230.38841, 231.706  , 232.75246, 231.8899 ,
       231.75002, 231.32022, 231.64684, 232.50697, 233.55042, 234.36835,
       234.64143, 234.83583, 233.00505, 231.65173, 230.4884 , 229.1002 ],
      dtype=float32)

In [115]:
nucaps_lats = nucaps.Latitude
nucaps_lons = nucaps.Longitude

### 5.2.2 GRIB2

In [116]:
filter_keys = {"filter_by_keys": {"typeOfLevel": "isobaricInhPa", "name": "Temperature"}}

In [117]:
gfs_xr = xr.open_dataset(gfs_file, engine="cfgrib", backend_kwargs=filter_keys)
print(gfs_xr)

<xarray.Dataset> Size: 9MB
Dimensions:        (isobaricInhPa: 33, latitude: 181, longitude: 360)
Coordinates:
  * isobaricInhPa  (isobaricInhPa) float64 264B 1e+03 975.0 950.0 ... 2.0 1.0
  * latitude       (latitude) float64 1kB 90.0 89.0 88.0 ... -88.0 -89.0 -90.0
  * longitude      (longitude) float64 3kB 0.0 1.0 2.0 3.0 ... 357.0 358.0 359.0
    time           datetime64[ns] 8B ...
    step           timedelta64[ns] 8B ...
    valid_time     datetime64[ns] 8B ...
Data variables:
    t              (isobaricInhPa, latitude, longitude) float32 9MB ...
Attributes:
    GRIB_edition:            2
    GRIB_centre:             kwbc
    GRIB_centreDescription:  US National Weather Service - NCEP
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             US National Weather Service - NCEP
    history:                 2026-01-17T13:58 GRIB to CDM+CF via cfgrib-0.9.1...

### 5.2.3 Accessing datasets using OpenDAP

In [119]:
url = "http://psl.noaa.gov/thredds/dodsC/Datasets/noaa.ersst.v6/sst.mnmean.nc"
ersst = xr.open_dataset(url)
print(ersst)

<xarray.Dataset> Size: 135MB
Dimensions:    (time: 2100, nbnds: 2, lat: 89, lon: 180)
Coordinates:
  * time       (time) datetime64[ns] 17kB 1850-01-01 1850-02-01 ... 2024-12-01
  * lat        (lat) float32 356B 88.0 86.0 84.0 82.0 ... -84.0 -86.0 -88.0
  * lon        (lon) float32 720B 0.0 2.0 4.0 6.0 ... 352.0 354.0 356.0 358.0
Dimensions without coordinates: nbnds
Data variables:
    time_bnds  (time, nbnds) float64 34kB ...
    sst        (time, lat, lon) float32 135MB ...
Attributes: (12/41)
    climatology:                     Climatology is based on 1971-2000 SST, X...
    description:                     In situ data: ICOADS2.5 before 2007 and ...
    keywords_vocabulary:             NASA Global Change Master Directory (GCM...
    keywords:                        Earth Science > Oceans > Ocean Temperatu...
    instrument:                      Conventional thermometers
    source_comment:                  SSTs were observed by conventional therm...
    ...                              ...
    history:                         created 01/16/2025 by PSL using NCEI ERS...
    References:                      https://www.ncdc.noaa.gov/data-access/ma...
    summary:                         ERSSTv6 is developped based on v5, by re...
    comments:                        SSTs were observed by conventional therm...
    platform:                        Ship and Buoy SSTs from ICOADS R3.0.2 an...
    DODS_EXTRA.Unlimited_Dimension:  time